### ISSUE TITLE
Map SciJava module metadata to magicgui

### ISSUE THREAD

**Issue by ctrueden** [imagej/napari-imagej#1]
SciJava module items have various metadata, including:
* [x] name
* [x] label
* [x] type
* [x] min/max values
* [x] default values
* [ ] widget styles

We should map as many of these as possible to their [magicgui equivalents](https://napari.org/magicgui/usage/types_widgets.html).

For `required=false` parameters, we may want to use `Optional[...]` so that they are allowed to be unset.

**Comment by gselzer** [comment]
#8 does everything except for widget styles.

Adding widget styles could be a bigger effort. I'll look into it.

**Comment by ctrueden** [comment]
@gselzer Glad to see progress on this. I wouldn't worry much about the widget styles -- they are requests, not requirements. If magicgui has an equivalent for a particular style, use it, or if not, oh well too bad.

**Comment by gselzer** [comment]
@ctrueden it seems like styles are covered by different magicgui widgets, instead of by an or property (am I right, @tlambert03?)
* The [`NumberWidget`](https://github.com/scijava/scijava-common/blob/309dc33241cefab2a2207ae31b32c8f137072996/src/main/java/org/scijava/widget/NumberWidget.java#L37) styles are covered by magicgui's [`SpinBox`](https://napari.org/magicgui/usage/_autosummary/magicgui.widgets.SpinBox.html) and [`Slider`](https://napari.org/magicgui/usage/_autosummary/magicgui.widgets.Slider.html)
* The [`ChoiceWidget`](https://github.com/scijava/scijava-common/blob/309dc33241cefab2a2207ae31b32c8f137072996/src/main/java/org/scijava/widget/ChoiceWidget.java#L37) styles are covered by [`ComboBox`](https://napari.org/magicgui/usage/_autosummary/magicgui.widgets.ComboBox.html), [`Select`](https://napari.org/magicgui/usage/_autosummary/magicgui.widgets.Select.html) and [`RadioButtons`](https://napari.org/magicgui/usage/_autosummary/magicgui.widgets.RadioButtons.html)
* The [`FileWidget`](https://github.com/scijava/scijava-common/blob/master/src/main/java/org/scijava/widget/FileWidget.java) styles do not seem to have a magicgui equivalent; all file selection is done by [`FileEdit`](https://napari.org/magicgui/usage/_autosummary/magicgui.widgets.FileEdit.html)

Thus we could support *some* styles by mapping types to a `widget_type`, passed [here](https://github.com/imagej/napari-imagej/blob/ae96833b99787dc41e12fb508c965152c15a658f/src/napari_imagej/_module_utils.py#L388) to magicgui. 

Unfortunately, this strategy would be a problem if widget styles ever map to a particular magicgui widget's options. In that case, we'd instead have to add a key to [`_add_param_metadata`](https://github.com/imagej/napari-imagej/blob/ae96833b99787dc41e12fb508c965152c15a658f/src/napari_imagej/_module_utils.py#L473). This would then require another dict, mapping a style to a parameter key and value. But also doable.

I'll start prototyping.

**Comment by gselzer** [comment]
> Thus we could support _some_ styles by mapping types to a `widget_type`, passed [here](https://github.com/imagej/napari-imagej/blob/ae96833b99787dc41e12fb508c965152c15a658f/src/napari_imagej/_module_utils.py#L388) to magicgui.

Actually, I think it becomes even easier as `widget_type` just gets thrown into the `options` [here](https://github.com/napari/magicgui/blob/b17aeb0906abd5deeb9590b45108d6c0ed12cb3e/magicgui/widgets/_bases/create_widget.py#L88). So we *should* just be able to specify `widget_type` in `_add_param_metadata`!
