### ISSUE TITLE
Some commands seem to get stuck

### ISSUE THREAD

**Issue by hinerm** [imagej/napari-imagej#202]
1. Open `bricks` sample image
2. Run `gauss(Img, Img, double[]) -> img` Op (highlighted in yellow)
3. Don't add any sigmas, or add a sigma. In either case:
4. Progress stuck at 33%

![image](https://user-images.githubusercontent.com/1123809/233717290-75d1f5a6-32ed-47f6-bbc6-6d9833e5fd3e.png)

However, if you instead run `gauss(Img, Img, Double, OOBF) -> Img` it seems to work fine:
![image](https://user-images.githubusercontent.com/1123809/233717502-8fba8ed6-a088-48da-95c9-8ab610385939.png)

Frangi vesselness (running on the first image of `Embro.tif`) also got stuck after appearing to do all of its work and complete.

**Comment by gselzer** [comment]
So I can replicate this @hinerm, and there are two problems going on. The issue is that you need to pass through a `sigmas` list with the same size as the number of dimensions in your image for that Op. But two things are happening:
1) The progress bar is shown as in-progress while the module aborted.
2) The error did not make its way to the user.

Let's see if I can't fix this

**Comment by gselzer** [comment]
scijava/scijava-common#459 should enable us to get the error to the user, and we can create a new `EventSubscriber` to close the progress-bar on cancel.

So we will just have to wait for the resolution of that PR.
