### ISSUE TITLE
No Image Open error when running ImageJ commands

### ISSUE THREAD

**Issue by hinerm** [imagej/napari-imagej#203]
1. Open napari
2. Open `brick`
3. Run `Gaussian Blur...` command (highlighted in yellow)
4. Get `No Image` error

![image](https://user-images.githubusercontent.com/1123809/233718123-1a05a180-9799-40b4-b560-57c634353ae8.png)

I'm assuming this command needs to be run from the ImageJ GUI because it needs an `ImageWindow`? We probably don't want to show any Ij1 commands then right..?

**Comment by gselzer** [comment]
> 1. Open napari
> 
>     2. Open `brick`
> 
>     3. Run `Gaussian Blur...` command (highlighted in yellow)
> 
>     4. Get `No Image` error
> 
> 
> ![image](https://user-images.githubusercontent.com/1123809/233718123-1a05a180-9799-40b4-b560-57c634353ae8.png)
> 
> I'm assuming this command needs to be run from the ImageJ GUI because it needs an `ImageWindow`? We probably don't want to show any Ij1 commands then right..?

@hinerm so what we *can* do is use the `LegacyImageMap` to set the current ImagePlus to the current active layer on the fly, so that these things would work. I think I started doing this on the `active-layer-to-active-ij-window` branch with [this commit](https://github.com/imagej/napari-imagej/commit/3062c5ce951d98f553fa9a9efec4557744ec0b64). I never did finish that work, though...

**Comment by gselzer** [comment]
I'm closing this, as #207 has been merged.
