### ISSUE TITLE
Error with SNT endpoint

### ISSUE THREAD

**Issue by kephale** [imagej/napari-imagej#211]
Testing endpoint: `net.imagej:imagej:2.9.0+org.morphonets:SNT:4.1.16`

Gives this error:
> ```[Errno 2] No such file or directory: '/Users/kharrington/.m2/repository/org/jzy3d/jzy3d-native-jogl-core/2.2.1/jzy3d-native-jogl-core-2.2.1-tests.test-jar' -> '/Users/kharrington/.jgo/net.imagej/imagej/2.9.0/e54008d79786f76ac454ef21e0ab51eea30a2b1fbc5b0bb5bd8586e5c1534414/jzy3d-native-jogl-core-2.2.1-tests.test-jar'```

I guess this is probably either a SNT issue or jgo, but it wasn't obvious so I'm starting the issue here.

**Comment by gselzer** [comment]
Hmm, I was able to repeat this initially @kephale, but I reset my environment while trying to debug into jgo and now I can't reproduce this anymore. napari-imagej prevents the usage of `net.imagej:imagej:2.9.0` because we need bugfixes in new components, and `net.imagej:imagej:2.11.0+org.morphonets:SNT:4.1.16` works without errors.

Can you try to reproduce after running `git checkout main; git pull; mamba env update -f dev-environment.yml --prune`? If it persists, I'd guess it's a `jgo` failure, as your endpoint looks correct, and I was getting the error within `jgo.resolve_dependencies`...

**Comment by kephale** [comment]
This endpoint works: `org.scijava:scijava-common:2.94.0+io.scif:scifio:0.45.0+org.scijava:scijava-search:2.0.2+net.imagej:imagej-legacy:1.1.0+net.imagej:imagej:2.11.0+org.morphonets:SNT:4.1.17`, aside from an error I get from `jzy3d-core-2.2.1-tests.test-jar` missing (which seems like an odd file). That missing file error is clearly from SNT, and I was able to resolve it by creating a duplicate of `jzy3d-core-2.2.1-tests.jar` as `jzy3d-core-2.2.1-tests.test-jar`

**Comment by ctrueden** [comment]
Simpler endpoints which might work:
* `net.imagej:imagej:2.13.0+org.morphonets:SNT:MANAGED`
* `sc.fiji:fiji:2.13.0+org.morphonets:SNT:MANAGED`

Version 2.13.0 (of either) comes with scijava-common 2.94.0, scifio 0.45.0, scijava-search 2.0.3, and imagej-legacy 1.1.0, so you wouldn't have to declare those upgrades manually anymore.
