### ISSUE TITLE
Selected result doesn't update after searching

### ISSUE THREAD

**Issue by hinerm** [imagej/napari-imagej#52]
![selected-doesnt-update](https://user-images.githubusercontent.com/1123809/170529958-611e0371-d047-4ddf-a814-a993d6de44e0.png)

To reproduce this image:
1. search for AddDimension
2. select `View: AddDimension`
3. search for `frangi`

At this point it looks like frangi is selected, but we actually still have AddDimension selected.

Also both the `Ops` and `modules` panes seem to track selection separately:
![image](https://user-images.githubusercontent.com/1123809/170530293-84c18719-098a-4553-973b-95e91064198a.png)

I think:
- selections in one pane should clear selection in the other
- searching should clear the "staged" selection for creating widgets

**Comment by ctrueden** [comment]
I agree that the search results list boxes should be better. IIRC, the way we do it in ImageJ2 is with a single `JList` with different sections, so that only one can be selected at a time. This may require more customization of the Qt component. And at that point, I start wondering whether our time would be better spent working on #39...
