### ISSUE TITLE
Ensure that errors in Java appear coherently within napari

### ISSUE THREAD

**Issue by gselzer** [imagej/napari-imagej#77]
Errors in e.g. module execution do not appear as popups in napari; they are only printed on the console. They should appear in napari as well.

See [this zulip thread](https://napari.zulipchat.com/#narrow/stream/309872-plugins/topic/Remaining.20napari-imagej.20issues.20for.200.2E1.2E0.20release/near/289225174) for context.

**Comment by gselzer** [comment]
@ctrueden so I dug into the issue a bit. napari tries to get the message of the exception [here](https://github.com/napari/napari/blob/67c50a4bec99d6a0f381276195ccc1ee1210b876/napari/utils/notifications.py#L148). Unfortunately, for Java exceptions, `message` is a *method*, not a *field*! The reason we don't get a popup is due to an error resulting from this discrepancy.

The easiest way forward is probably to just wrap Java exceptions as Python exceptions and just raise those :frowning:

**Comment by ctrueden** [comment]
I would suggest filing an issue in the JPype issue tracker about this discrepancy. Specifically: can we add `@property` to the [`message(self)` method](https://github.com/jpype-project/jpype/blob/v1.4.0/jpype/_jexception.py#L36-L38) so that `msg = getattr(exception, 'message', str(exception))` works as desired without special casing it on the napari side? (I tested it, and with the `@property` decorator, this `getattr` invocation works as desired.)

**Comment by ctrueden** [comment]
> wrap Java exceptions as Python exceptions and just raise those

I am supportive of that, as long as we use `scyjava.jstacktrace` for the message of the Python exception, so that the entire Java stack trace is preserved.

**Comment by gselzer** [comment]
> > wrap Java exceptions as Python exceptions and just raise those
> 
> I am supportive of that, as long as we use `scyjava.jstacktrace` for the message of the Python exception, so that the entire Java stack trace is preserved.

:+1:

There's an issue with my testing right now, though. `ScriptModule` doesn't actually throw `Exception`s raised within scripts, it just [prints their traces](https://github.com/scijava/scijava-common/blob/d50ae5b31d8912eeab9adbb62a8ee966c0c10c83/src/main/java/org/scijava/script/ScriptModule.java#L166)!

**Comment by ctrueden** [comment]
Yeah, the reason is so that the Script Editor, which had an existing stdout/stderr infrastructure already before SciJava came along, can still dump those streams to its text console. Unfortunately, there is no unified `Module`-level way of telling the framework to use your custom streams (which would allow you to then pass along this output to napari somehow more easily).

We might want to raise the issue of stdout/stderr with the napari folks, to see if they see any value in including a GUI stdout/stderr console inside napari, which pops up to the user when anything appears on stderr. This would solve our issue, and be more general besides. There will probably be pushback that there is already a console on the terminal when launching napari, but this rebuttal does not take into account the (future most common) use case of launching napari via a desktop icon.

**Comment by ctrueden** [comment]
Another thing we could do is update the SciJava script framework to actually throw those exceptions unless custom streams were provided for dumping them instead.

**Comment by ctrueden** [comment]
> Woah, can we do that without breaking backwards compatibility?

Ahh, I didn't realize that if you add `@property` to something, then calling it as a method no longer works. Too bad. But maybe worth asking anyway?

**Comment by gselzer** [comment]
> Another thing we could do is update the SciJava script framework to actually throw those exceptions unless custom streams were provided for dumping them instead.

I like this idea better. Customization seems better and would allow us to proceed without effort on napari.

**Comment by ctrueden** [comment]
> python's [BaseException](https://docs.python.org/3/library/exceptions.html#BaseException) doesn't have an attribute for accessing the message at all, it's just part of napari's assumptions

Oof, thanks for clarifying that. Then yeah, it makes no sense to change it in JPype.

**Comment by Thrameos** [comment]
I checked.  ``message`` appears to always have been a function in JPype1 going back to 0.6.3.   (it was totally inconsistent with the rest of the code at the time, so it likely should have had ``@property``)  Currently, it is a legacy method from when the Java and Python exceptions were split.   I recommend using the better named ``getMessage`` function as it is less likely to cause confusion.
